### ISSUE TITLE
In-use kernel removed

### ISSUE THREAD

**Issue by apascualgarcia** [rubo77/remove-old-kernels#1]
Hi there,

Thanks for your script. I am having the following issue when I run it, for some reason the grep -v  statement to skip removing the in-use kernel doesn't work:

```
$ ./remove_old_kernels.sh 
Linux adelina 4.15.0-213-generic #224-Ubuntu SMP Mon Jun 19 13:30:12 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
Your in use kernel is **4.15.0-213-generic**
Old Kernels to be removed:
linux-headers-4.15.0-212
linux-headers-4.15.0-212-generic
linux-image-4.15.0-10-generic
linux-image-4.15.0-101-generic
linux-image-4.15.0-106-generic
linux-image-4.15.0-108-generic
linux-image-4.15.0-109-generic
linux-image-4.15.0-111-generic
linux-image-4.15.0-112-generic
linux-image-4.15.0-115-generic
linux-image-4.15.0-117-generic
linux-image-4.15.0-118-generic
linux-image-4.15.0-12-generic
linux-image-4.15.0-122-generic
**linux-image-4.15.0-123-generic**
....
```

Same for the modules. It works if I manually include the label 4.15.0-213 in the code.

Thanks in advance for your help

**Comment by rubo77** [comment]
maybe you don't have awk installed?

what happens if you enter 

       uname -a | awk '{ print $3 }'

**Comment by apascualgarcia** [comment]
Thanks for your answer,

I do have awk installed and it correctly returns the kernel. Indeed,  the output of the script (I highlighted it with **) correctly returns the kernel. This is why I suggested that the problem was with grep.

**Comment by rubo77** [comment]
I think you misread the detailed version number: 4.15.0-213 != 4.15.0-123  ;)

**Comment by apascualgarcia** [comment]
OMG, I am really sorry... Sleep depravation.
